name: update
on:
  workflow_dispatch:
  push:
jobs:
  update:
    runs-on: macos-latest
    permissions: write-all
    env:
      GH_TOKEN: ${{ github.token }}
    steps:
        - uses: actions/checkout@v4.2.2
        - run: git tag -f latest && git push && git push origin -f latest && gh run delete $(gh run list --json databaseId -q "map(.databaseId)[1]")

